version: "3.8"

services:
  biddy_gunicorn:
    build: 
      context: ./Biddy
    volumes:
      - static:/app/static  # Utilisation de /app/static pour les fichiers statiques
      - images:/app/images  # Utilisation de /app/images pour les fichiers media
    env_file:
      - Biddy/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}  # Utilisation des variables d'environnement

  rasa:
    build:
      context: ./BiddyBot/BiddyBot
    ports:
      - "5005:5005"
    depends_on:
      - action_server

  action_server:
    build:
      context: ./BiddyBot/actions  # Assurez-vous que ce chemin contient le Dockerfile pour le serveur d'actions
    ports:
      - "5055:5055"
    volumes:
      - ./BiddyBot/actions:/app/actions  # Assurez-vous que ce chemin contient vos fichiers d'actions personnalisées
    environment:
      - PYTHONUNBUFFERED=1  # Bonne pratique pour les logs en temps réel

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static  # Utilisation de /app/static pour les fichiers statiques
      - images:/app/images  # Utilisation de /app/images pour les fichiers media
    ports:
      - "80:80"
    depends_on:
      - biddy_gunicorn

  db:
    image: postgres:17rc1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  static:
  images:  # Volume pour stocker les fichiers media
  postgres_data:
