version: "3.8"

services:
  biddy_gunicorn:
    build: 
      context: ./Biddy
    volumes:
      - static:/app/static
      - images:/app/images
    env_file:
      - Biddy/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  
  rasa:
    build:
      context: ../Chatbots/BiddyBot/BiddyBot
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ../Chatbots/BiddyBot/BiddyBot:/app
    environment:
      - PYTHONUNBUFFERED=1

  action_server:
    build:
      context: ../Chatbots/BiddyBot/BiddyBot
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ../Chatbots/BiddyBot/BiddyBot/actions:/app/actions
    depends_on:
      - rasa
    environment:
      - PYTHONUNBUFFERED=1  # Assurez-vous que les logs sont affichés en temps réel

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - images:/app/images
    ports:
      - "80:80"
    depends_on:
      - biddy_gunicorn

  db:
    image: postgres:17rc1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  static:
  images:
  postgres_data:
